C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/8,7/
      DATA (SPROP(I,-1,1),I=1,1)/-24/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,6/
      DATA (SPROP(I,-2,1),I=1,1)/-6/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/5,4/
      DATA (SPROP(I,-3,1),I=1,1)/24/
      DATA TPRID(-3,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/-3,3/
      DATA (SPROP(I,-4,1),I=1,1)/6/
      DATA TPRID(-4,1)/0/
      DATA (IFOREST(I,-5,1),I=1,2)/-2,-4/
      DATA (SPROP(I,-5,1),I=1,1)/21/
      DATA TPRID(-5,1)/0/
C     Number of configs
      DATA MAPCONFIG(0)/1/
